### ISSUE TITLE
Regex matching of arguments being passed 

### ISSUE THREAD

**Issue by nitinsurana** [capitalone/bash_shell_mock#10]
```
node -e "require('./helper').validate()"
```
Above is how my function call looks. I can't seem to find a corresponding shellmock_expect --match argument. I've tried various combinations like : 
```
shellmock_expect node --status 1 --match '-e "require('./helper').validate()"'
shellmock_expect node --status 1 --match '-e "require(\'./helper\').validate()"'
shellmock_expect node --status 1 --match '-e "require(\"./helper\").validate()"'
``` 
throws status 99

**Comment by nitinsurana** [comment]
```
shellmock_expect node --status 1 --match "-e require('./helper').validate()"
```
works. Maybe we should update the readme with a complex example. Also, if there's a possibility to provide --match as a regex.

**Comment by ckstettler** [comment]
You were asking some good questions here.  I could definitely create a more complex example in the read me.  regex for the match seems interesting although sadly regex often confuse me.

I do that comparision in an awk script and awk has  a regex operator I think.  I could add another "type" x for regex evaluation.

**Comment by nitinsurana** [comment]
Great to know you agree with adding the regex support. Adding`type` parameter sounds like a good idea.

**Comment by ckstettler** [comment]
I am looking into this presently.  The usual escaping tricks not working I see.  I see one more to try and that is \\ which may allow the backslash to make it through to awk.  I will investigate.

**Comment by ckstettler** [comment]
@nitinsurana would you be willing to review the PR before its merged?  I think I have is covered.

**Comment by nitinsurana** [comment]
Yup sure.
