### ISSUE TITLE
Contributors agreement

### ISSUE THREAD

**Issue by ckstettler** [capitalone/bash_shell_mock#13]
@nitinsurana @jdorfman @particleflux @meustrus it seems I had the cart before the horse regarding CapitalOne's opensource contributor policy.  All contributors are suppose to complete a CLM prior to me accepting the PR.  Obviously that ship has sailed.

I have a PR to add this information within the repo for future contributors.  The link is here https://developer.capitalone.com/open-source/

Would you visit the site and read the CLM and if you can agree to it? If so then please submit one.  Much of the language is with regard to patent rights which I don't for see being an issue here.   I have valued your inputs so far and hope to see your continued use and support.  If you can't agree to it I certainly understand.

**Comment by nitinsurana** [comment]
@ckstettler Submitted!
For others, the CLA link is : 
https://docs.google.com/forms/d/19LpBBjykHPox18vrZvBbZUcK6gQTj7qv1O5hCduAZFU/viewform?edit_requested=true

**Comment by jdorfman** [comment]
@ckstettler please lmk if you need anything else.
