### ISSUE TITLE
Bash logo in README

### ISSUE THREAD

**Issue by jdorfman** [capitalone/bash_shell_mock#7]
Hi,

Before I make a PR I was wondering if you would be opposed to having the [official Bash logo](https://github.com/odb/official-bash-logo) in the readme? 

Here are some examples: https://github.com/odb/official-bash-logo#sightings

**Comment by ckstettler** [comment]
I am not opposed.

**Comment by jdorfman** [comment]
So it seems that GitHub ignores the `[.text-center]` && `align="center"` Asciidoctor attributes in `README.adoc` meaning it will stay left-aigned. Your call.

![image 2018-12-28 at 1 52 33 pm](https://user-images.githubusercontent.com/398230/50529339-091a9a80-0aa9-11e9-8ed5-d3e577876d91.png)
